version: "3.8"

services:
  app_web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app_web
    image: app_web:0.2
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    networks:
      - app_network
    platform: linux/amd64
    volumes:
      - ./:/rails

networks:
  app_network:
    external: true


